ATS_KEYWORD_HINTS = {
    "a/b testing",
    "accessibility",
    "account management",
    "agile",
    "ai",
    "analytics",
    "android",
    "api",
    "aws",
    "azure",
    "backend",
    "budgeting",
    "business analysis",
    "c#",
    "c++",
    "ci/cd",
    "cloud",
    "cold outreach",
    "communication",
    "crm",
    "css",
    "customer success",
    "data analysis",
    "data engineering",
    "data visualization",
    "devops",
    "django",
    "docker",
    "drizzle",
    "etl",
    "express",
    "fastapi",
    "figma",
    "firebase",
    "flask",
    "frontend",
    "gcp",
    "git",
    "graphql",
    "html",
    "ios",
    "java",
    "javascript",
    "kubernetes",
    "leadership",
    "llm",
    "machine learning",
    "marketing",
    "mongodb",
    "next.js",
    "node.js",
    "postgresql",
    "product management",
    "project management",
    "python",
    "react",
    "redux",
    "rest",
    "sales",
    "seo",
    "sql",
    "stakeholder management",
    "supabase",
    "tailwind",
    "typescript",
    "ui",
    "ux",
    "vercel",
    "vue",
}
