"""Equivalent terms used when finding shared resume and job concepts."""


SEMANTIC_ALIASES = {
    "api": {"apis", "rest", "graphql", "endpoint", "backend service"},
    "aws": {"cloud", "lambda", "ec2", "s3", "cloud infrastructure"},
    "azure": {"cloud", "cloud infrastructure"},
    "backend": {"server-side", "api", "service layer", "microservices"},
    "ci/cd": {"deployment pipeline", "continuous integration", "continuous delivery"},
    "cloud": {"aws", "azure", "gcp", "cloud infrastructure"},
    "crm": {"salesforce", "hubspot", "customer relationship management"},
    "data analysis": {"analytics", "reporting", "insights", "dashboards"},
    "data visualization": {"dashboards", "charts", "reporting", "bi"},
    "devops": {"ci/cd", "deployment", "infrastructure", "observability"},
    "fastapi": {"python api", "asgi", "backend api"},
    "frontend": {"ui", "client-side", "web interface", "react"},
    "gcp": {"cloud", "google cloud", "cloud infrastructure"},
    "javascript": {"js", "typescript", "frontend"},
    "kubernetes": {"k8s", "containers", "orchestration"},
    "leadership": {"led", "managed", "mentored", "owned"},
    "machine learning": {"ml", "ai", "models", "predictive"},
    "next.js": {"nextjs", "react", "server components"},
    "node.js": {"node", "express", "javascript runtime"},
    "postgresql": {"postgres", "sql", "relational database"},
    "product management": {"roadmap", "prioritization", "stakeholders"},
    "project management": {"delivery", "planning", "coordination"},
    "python": {"django", "flask", "fastapi", "python api"},
    "react": {"frontend", "ui", "component", "next.js"},
    "rest": {"api", "endpoint", "http api"},
    "sql": {"database", "postgresql", "mysql", "relational database"},
    "typescript": {"javascript", "type-safe", "frontend"},
    "ui": {"frontend", "interface", "components"},
    "ux": {"user experience", "usability", "research"},
}
