import { coldEmails, db, resumes } from "@repo/db";
import { and, eq } from "drizzle-orm";

import { ColdmailError } from "./coldmail-errors";
import { checkUsageLimit } from "@/modules/dashboard/server/usage-limits";
import { coldmailGenerationTask } from "@/trigger/coldmail-generation";
import type { ColdEmailGenerateInput } from "@repo/validations";

export const generateColdEmailForUser = async (
  input: ColdEmailGenerateInput & { userId: string },
) => {
  await checkUsageLimit(input.userId, "cold_email_generate");

  const resume = await db.query.resumes.findFirst({
    where: and(
      eq(resumes.id, input.resumeId),
      eq(resumes.userId, input.userId),
    ),
  });

  if (!resume) {
    throw new ColdmailError("Resume not found.", 404);
  }

  let savedColdmailId: string | null = null;

  try {
    // 1. Insert placeholder row in the DB
    const [savedColdmail] = await db
      .insert(coldEmails)
      .values({
        userId: input.userId,
        organizationId: resume.organizationId,
        resumeId: resume.id,
        jobTitle: input.jobTitle,
        companyName: input.companyName,
        companyWebsiteUrl: input.companyWebsiteUrl,
        recipientName: input.recipientName,
        recipientRole: input.recipientRole,
        jobDescription: input.jobDescription,
        companyContext: "", // Context generated by the AI step
        personalNote: input.personalNote,
        tone: input.tone,
        length: input.length,
        callToAction: input.callToAction,
        status: "processing",
      })
      .returning({ id: coldEmails.id });

    if (!savedColdmail) {
      throw new Error("Failed to save Cold Email record.");
    }

    savedColdmailId = savedColdmail.id;

    // 2. Queue the job in Trigger.dev
    await coldmailGenerationTask.trigger(
      {
        coldEmailId: savedColdmail.id,
        userId: input.userId,
      },
      {
        idempotencyKey: `coldmail-generation:${savedColdmail.id}`,
      },
    );

    // 3. Return the jobId so the frontend can poll it
    return {
      coldEmailId: savedColdmail.id,
      status: "processing",
    };
  } catch (error) {
    if (error instanceof ColdmailError) {
      throw error;
    }

    const message =
      error instanceof Error
        ? error.message
        : "Unknown Cold Email trigger error";

    if (savedColdmailId) {
      await db
        .update(coldEmails)
        .set({
          status: "failed",
          error: message,
        })
        .where(
          and(
            eq(coldEmails.id, savedColdmailId),
            eq(coldEmails.userId, input.userId),
          ),
        );
    }

    throw new ColdmailError(message, 502);
  }
};
