import { coldEmails, db, resumes } from "@repo/db";
import { tasks } from "@trigger.dev/sdk";
import { and, eq } from "drizzle-orm";

import { ColdmailError } from "./coldmail-errors";
import {
  releaseUsage,
  reserveUsage,
} from "@/modules/dashboard/server/usage-limits";
import type { coldmailGenerationTask } from "@/trigger/coldmail-generation";
import type { ColdEmailGenerateInput } from "@repo/validations";
import { logRouteError } from "@/lib/server/api-errors";

export const generateColdEmailForUser = async (
  input: ColdEmailGenerateInput & { userId: string },
) => {
  const resume = await db.query.resumes.findFirst({
    where: and(
      eq(resumes.id, input.resumeId),
      eq(resumes.userId, input.userId),
    ),
  });

  if (!resume) {
    throw new ColdmailError("Resume not found.", 404);
  }

  let savedColdmailId: string | null = null;

  try {
    // 1. Insert placeholder row in the DB
    const [savedColdmail] = await db
      .insert(coldEmails)
      .values({
        userId: input.userId,
        resumeId: resume.id,
        jobTitle: input.jobTitle || "Job Opening",
        companyName: input.companyName || "Unknown",
        companyWebsiteUrl: input.companyWebsiteUrl || "",
        recipientName: input.recipientName || "Hiring Manager",
        recipientRole: input.recipientRole || "Recruiter",
        jobDescription: input.jobDescription || "",
        companyContext: "", // Context generated by the AI step
        tone: input.tone || "warm",
        length: input.length || "standard",
        callToAction: input.callToAction || "conversation",
        status: "processing",
      })
      .returning({ id: coldEmails.id });

    if (!savedColdmail) {
      throw new Error("Failed to save Cold Email record.");
    }

    savedColdmailId = savedColdmail.id;

    await reserveUsage(input.userId, "cold_email_generate", savedColdmail.id);

    // 2. Queue the job in Trigger.dev
    await tasks.trigger<typeof coldmailGenerationTask>(
      "coldmail-generation",
      {
        coldEmailId: savedColdmail.id,
        userId: input.userId,
      },
      {
        idempotencyKey: `coldmail-generation:${savedColdmail.id}`,
      },
    );

    // 3. Return the jobId so the frontend can poll it
    return {
      coldEmailId: savedColdmail.id,
      status: "processing",
    };
  } catch (error) {
    if (error instanceof ColdmailError) {
      throw error;
    }

    logRouteError("Failed to queue cold email generation", error);
    const message = "Unable to start cold email generation right now.";

    if (savedColdmailId) {
      await releaseUsage(savedColdmailId);
      await db
        .update(coldEmails)
        .set({
          status: "failed",
          error: message,
        })
        .where(
          and(
            eq(coldEmails.id, savedColdmailId),
            eq(coldEmails.userId, input.userId),
          ),
        );
    }

    throw new ColdmailError(message, 502);
  }
};
